/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GPv2Settlement } from './GPv2Settlement'

export { GPv2Settlement__factory } from './factories/GPv2Settlement__factory'
