packages:
  - 'apps/*'
  - 'libs/*'

patchedDependencies:
  '@synthetixio/synpress-metamask@0.0.11': patches/@synthetixio__synpress-metamask@0.0.11.patch
  '@reown/appkit-adapter-wagmi@1.8.19': patches/@reown__appkit-adapter-wagmi@1.8.19.patch
  '@wagmi/core@3.4.8': patches/@wagmi__core@3.4.8.patch
