/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import { Provider } from '@ethersproject/providers'
import type { SafeWalletContract, SafeWalletContractInterface } from '../SafeWalletContract'

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'txHash',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'payment',
        type: 'uint256',
      },
    ],
    name: 'ExecutionSuccess',
    type: 'event',
  },
]

export class SafeWalletContract__factory {
  static readonly abi = _abi
  static createInterface(): SafeWalletContractInterface {
    return new utils.Interface(_abi) as SafeWalletContractInterface
  }
  static connect(address: string, signerOrProvider: Signer | Provider): SafeWalletContract {
    return new Contract(address, _abi, signerOrProvider) as SafeWalletContract
  }
}
