const BALANCES_WATCHER_BASE_URL_DEFAULT = 'https://balance-watcher.info'

export const BALANCES_WATCHER_BASE_URL =
  process.env['REACT_APP_BALANCES_WATCHER_BASE_URL'] || BALANCES_WATCHER_BASE_URL_DEFAULT
