const BALANCES_AGGREGATOR_BASE_URL_DEFAULT = 'http://localhost:8090'

export const BALANCES_AGGREGATOR_BASE_URL =
  process.env['REACT_APP_BALANCES_AGGREGATOR_BASE_URL'] || BALANCES_AGGREGATOR_BASE_URL_DEFAULT
