export { HighSuggestedSlippageWarning } from './containers/HighSuggestedSlippageWarning'
export * from './hooks/useSetSlippage'
export * from './hooks/useTradeSlippage'
export * from './hooks/useIsSmartSlippageApplied'
export * from './hooks/useIsSlippageModified'
export * from './hooks/useSetSmartSlippageEnabledByWidget'
