export { useSingleContractMultipleData } from './hooks/useSingleContractMultipleData'
export { useMultipleContractSingleData } from './hooks/useMultipleContractSingleData'
export { getMulticallContract } from './utils/getMulticallContract'
export { multiCall } from './multiCall'
export type { MultiCallOptions } from './multiCall'
