/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type { CoWSettlement, CoWSettlementInterface } from '../CoWSettlement'

const _abi = [
  {
    inputs: [],
    name: 'domainSeparator',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const

export class CoWSettlement__factory {
  static readonly abi = _abi
  static createInterface(): CoWSettlementInterface {
    return new utils.Interface(_abi) as CoWSettlementInterface
  }
  static connect(address: string, signerOrProvider: Signer | Provider): CoWSettlement {
    return new Contract(address, _abi, signerOrProvider) as CoWSettlement
  }
}
