/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Erc20_bytes32, Erc20_bytes32Interface } from "../Erc20_bytes32";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "name",
    outputs: [
      {
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "symbol",
    outputs: [
      {
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Erc20_bytes32__factory {
  static readonly abi = _abi;
  static createInterface(): Erc20_bytes32Interface {
    return new utils.Interface(_abi) as Erc20_bytes32Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Erc20_bytes32 {
    return new Contract(address, _abi, signerOrProvider) as Erc20_bytes32;
  }
}
