import { ComponentType, lazy, type LazyExoticComponent } from 'react'

import type { CowSwapWidgetProps } from '@cowprotocol/widget-lib'

import type { WidgetSdkVersion } from './widget-sdk-versions.constants'

type CowSwapWidgetComponent = ComponentType<CowSwapWidgetProps>

type PinnedWidgetSdkVersion = Exclude<WidgetSdkVersion, 'local'>

// --- AUTO-GENERATED by widget-sdk-versions.script (do not edit) ---
export const LAZY_WIDGETS_BY_VERSION: Record<PinnedWidgetSdkVersion, LazyExoticComponent<CowSwapWidgetComponent>> = {
  '3.2.0': lazy(() =>
    import('widget-react-v3.2.0').then((module) => ({
      default: module.CowSwapWidget as CowSwapWidgetComponent,
    })),
  ),
  '2.0.2': lazy(() =>
    import('widget-react-v2.0.2').then((module) => ({
      default: module.CowSwapWidget as CowSwapWidgetComponent,
    })),
  ),
  '1.3.5': lazy(() =>
    import('widget-react-v1.3.5').then((module) => ({
      default: module.CowSwapWidget as CowSwapWidgetComponent,
    })),
  ),
  '0.13.0': lazy(() =>
    import('widget-react-v0.13.0').then((module) => ({
      default: module.CowSwapWidget as CowSwapWidgetComponent,
    })),
  ),
}
// --- END AUTO-GENERATED ---
