import type { SelectInputOption } from '../../components/ui/inputs/Select/base/BaseSelectInput.types'

// --- AUTO-GENERATED by widget-sdk-versions.script (do not edit) ---
/** Workspace widget-react and widget-lib versions (keep in sync with libs package.json files). */
export const LOCAL_WIDGET_REACT_VERSION = '3.0.5' as const
export const LOCAL_WIDGET_LIB_VERSION = '4.0.5' as const

/** Latest published @cowprotocol/widget-react on npm. */
export const NPM_WIDGET_REACT_LATEST_VERSION = '3.0.5' as const

/** @cowprotocol/widget-lib version bundled by {@link NPM_WIDGET_REACT_LATEST_VERSION} on npm. */
export const NPM_WIDGET_LIB_LATEST_VERSION = '4.0.5' as const
// --- END AUTO-GENERATED ---

/** First @cowprotocol/widget-react release whose widget-lib posts READY to the parent page. */
export const NPM_WIDGET_REACT_FIRST_VERSION_WITH_ON_READY = '3.0.5' as const

// --- AUTO-GENERATED PINNED LEGACY by widget-sdk-versions.script (do not edit) ---
/** Legacy pinned npm releases and their widget-lib versions. */
export const PINNED_LEGACY_WIDGET_SDK_META = {
  '2.0.2': {
    widgetReactVersion: '2.0.2',
    widgetLibVersion: '3.1.1',
  },
  '1.3.5': {
    widgetReactVersion: '1.3.5',
    widgetLibVersion: '2.2.5',
  },
  '0.13.0': {
    widgetReactVersion: '0.13.0',
    widgetLibVersion: '0.18.0',
  },
} as const
// --- END AUTO-GENERATED PINNED LEGACY ---

export type PinnedLegacyWidgetSdkVersion = keyof typeof PINNED_LEGACY_WIDGET_SDK_META

export const PINNED_LEGACY_WIDGET_SDK_VERSIONS = Object.keys(
  PINNED_LEGACY_WIDGET_SDK_META,
) as PinnedLegacyWidgetSdkVersion[]

export type WidgetSdkVersion = 'local' | typeof NPM_WIDGET_REACT_LATEST_VERSION | PinnedLegacyWidgetSdkVersion

export interface WidgetSdkVersionMeta {
  /** @cowprotocol/widget-react version (first number in the label). */
  widgetReactVersion: string
  /** @cowprotocol/widget-lib range/version declared by that widget-react release on npm. */
  widgetLibVersion: string
}

export const WIDGET_SDK_VERSION_META: Record<WidgetSdkVersion, WidgetSdkVersionMeta> = {
  local: {
    widgetReactVersion: LOCAL_WIDGET_REACT_VERSION,
    widgetLibVersion: LOCAL_WIDGET_LIB_VERSION,
  },
  [NPM_WIDGET_REACT_LATEST_VERSION]: {
    widgetReactVersion: NPM_WIDGET_REACT_LATEST_VERSION,
    widgetLibVersion: NPM_WIDGET_LIB_LATEST_VERSION,
  },
  ...PINNED_LEGACY_WIDGET_SDK_META,
}

export const WIDGET_SDK_VERSION_VALUES: WidgetSdkVersion[] = [
  'local',
  NPM_WIDGET_REACT_LATEST_VERSION,
  ...PINNED_LEGACY_WIDGET_SDK_VERSIONS,
]

export function getPinnedWidgetReactPackageName(version: Exclude<WidgetSdkVersion, 'local'>): string {
  return `widget-react-v${version}`
}

function formatWidgetSdkVersionLabel(title: string, meta: WidgetSdkVersionMeta): string {
  return `${title} (react = ${meta.widgetReactVersion}, lib = ${meta.widgetLibVersion})`
}

function getSdkVersionDisplayTitle(version: WidgetSdkVersion): string {
  if (version === 'local') return 'Local'

  if (version === NPM_WIDGET_REACT_LATEST_VERSION) return 'Latest'

  return WIDGET_SDK_VERSION_META[version].widgetReactVersion
}

const ALL_SDK_VERSION_OPTIONS: SelectInputOption<WidgetSdkVersion>[] = WIDGET_SDK_VERSION_VALUES.map((value) => ({
  label: formatWidgetSdkVersionLabel(getSdkVersionDisplayTitle(value), WIDGET_SDK_VERSION_META[value]),
  value,
}))

/** Keep in sync with {@link isLocalHost} in configurator.constants. */
const isWidgetSdkLocalHost = ['localhost', '127.0.0.1'].includes(window.location.hostname)

/** The `local` workspace build is only meaningful (and selectable) during local development. */
export const SDK_VERSION_OPTIONS: SelectInputOption<WidgetSdkVersion>[] = isWidgetSdkLocalHost
  ? ALL_SDK_VERSION_OPTIONS
  : ALL_SDK_VERSION_OPTIONS.filter((option) => option.value !== 'local')

export const VALID_WIDGET_SDK_VERSIONS = new Set<WidgetSdkVersion>(WIDGET_SDK_VERSION_VALUES)
