#!/usr/bin/env node

/**
 * Syncs widget SDK version constants with the workspace libs and npm latest release.
 *
 * Usage:
 *   node apps/widget-configurator/scripts/widget-sdk-versions.script.mjs
 *
 * Or via pnpm:
 *   pnpm update-widget-sdk-versions
 */

import fs from 'node:fs'
import https from 'node:https'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const WIDGET_CONFIGURATOR_ROOT = path.resolve(__dirname, '..')
const REPO_ROOT = path.resolve(WIDGET_CONFIGURATOR_ROOT, '../..')

const PATHS = {
  constants: path.join(
    WIDGET_CONFIGURATOR_ROOT,
    'src/utils/widget-sdk-versions/widget-sdk-versions.constants.ts',
  ),
  loaders: path.join(WIDGET_CONFIGURATOR_ROOT, 'src/utils/widget-sdk-versions/widget-sdk-versions.loaders.ts'),
  declarations: path.join(WIDGET_CONFIGURATOR_ROOT, 'src/declarations.d.ts'),
  packageJson: path.join(WIDGET_CONFIGURATOR_ROOT, 'package.json'),
  widgetReactPkg: path.join(REPO_ROOT, 'libs/widget-react/package.json'),
  widgetLibPkg: path.join(REPO_ROOT, 'libs/widget-lib/package.json'),
}

const AUTO_GENERATED_BEGIN = '// --- AUTO-GENERATED by widget-sdk-versions.script (do not edit) ---'
const AUTO_GENERATED_END = '// --- END AUTO-GENERATED ---'
const PINNED_LEGACY_BEGIN = '// --- AUTO-GENERATED PINNED LEGACY by widget-sdk-versions.script (do not edit) ---'
const PINNED_LEGACY_END = '// --- END AUTO-GENERATED PINNED LEGACY ---'

function fetchJson(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers: { 'User-Agent': 'cowswap-widget-sdk-versions-updater' } }, (response) => {
        if (response.statusCode >= 300 && response.statusCode < 400 && response.headers.location) {
          fetchJson(response.headers.location).then(resolve, reject)
          return
        }

        if (response.statusCode !== 200) {
          reject(new Error(`HTTP ${response.statusCode} from ${url}`))
          return
        }

        let data = ''
        response.on('data', (chunk) => {
          data += chunk
        })
        response.on('end', () => {
          try {
            resolve(JSON.parse(data))
          } catch (error) {
            reject(error)
          }
        })
      })
      .on('error', reject)
  })
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'))
}

function replaceAutoGeneratedBlock(filePath, beginMarker, endMarker, content) {
  const source = fs.readFileSync(filePath, 'utf8')
  const pattern = new RegExp(`${escapeRegExp(beginMarker)}[\\s\\S]*?${escapeRegExp(endMarker)}`, 'm')

  if (!pattern.test(source)) {
    throw new Error(`Missing auto-generated block in ${filePath}`)
  }

  fs.writeFileSync(filePath, source.replace(pattern, content.trim()))
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function stripSemverRange(versionRange) {
  return versionRange.replace(/^[\^~>=<]+/, '')
}

async function getNpmPackageVersion(packageName, versionTag = 'latest') {
  const url = `https://registry.npmjs.org/${packageName}/${versionTag}`
  const data = await fetchJson(url)
  return data.version
}

async function getWidgetLibVersionForWidgetReact(widgetReactVersion) {
  const url = `https://registry.npmjs.org/@cowprotocol/widget-react/${widgetReactVersion}`
  const data = await fetchJson(url)
  const widgetLibRange = data.dependencies?.['@cowprotocol/widget-lib']

  if (!widgetLibRange) {
    throw new Error(`Could not resolve @cowprotocol/widget-lib for @cowprotocol/widget-react@${widgetReactVersion}`)
  }

  return stripSemverRange(widgetLibRange)
}

function getLegacyPinnedVersions(constantsSource) {
  const legacySection = constantsSource.split(PINNED_LEGACY_BEGIN)[1]?.split(PINNED_LEGACY_END)[0] ?? ''

  return [...legacySection.matchAll(/'(\d+\.\d+\.\d+)': \{/g)].map((match) => match[1])
}

function buildConstantsBlock({
  localWidgetReactVersion,
  localWidgetLibVersion,
  npmWidgetReactLatestVersion,
  npmWidgetLibLatestVersion,
}) {
  return `${AUTO_GENERATED_BEGIN}
/** Workspace widget-react and widget-lib versions (keep in sync with libs package.json files). */
export const LOCAL_WIDGET_REACT_VERSION = '${localWidgetReactVersion}' as const
export const LOCAL_WIDGET_LIB_VERSION = '${localWidgetLibVersion}' as const

/** Latest published @cowprotocol/widget-react on npm. */
export const NPM_WIDGET_REACT_LATEST_VERSION = '${npmWidgetReactLatestVersion}' as const

/** @cowprotocol/widget-lib version bundled by {@link NPM_WIDGET_REACT_LATEST_VERSION} on npm. */
export const NPM_WIDGET_LIB_LATEST_VERSION = '${npmWidgetLibLatestVersion}' as const
${AUTO_GENERATED_END}`
}

function buildPinnedLegacyBlock(legacyVersions, widgetLibVersionsByVersion) {
  const entries = legacyVersions
    .map(
      (version) => `  '${version}': {
    widgetReactVersion: '${version}',
    widgetLibVersion: '${widgetLibVersionsByVersion[version]}',
  },`,
    )
    .join('\n')

  return `${PINNED_LEGACY_BEGIN}
/** Legacy pinned npm releases and their widget-lib versions. */
export const PINNED_LEGACY_WIDGET_SDK_META = {
${entries}
} as const
${PINNED_LEGACY_END}`
}

function buildLoaderEntry(version) {
  const packageName = `widget-react-v${version}`
  return `  '${version}': lazy(() =>
    import('${packageName}').then((module) => ({
      default: module.CowSwapWidget as CowSwapWidgetComponent,
    })),
  ),`
}

function buildLoadersBlock(pinnedVersions) {
  const entries = pinnedVersions.map(buildLoaderEntry).join('\n')

  return `${AUTO_GENERATED_BEGIN}
export const LAZY_WIDGETS_BY_VERSION: Record<PinnedWidgetSdkVersion, LazyExoticComponent<CowSwapWidgetComponent>> = {
${entries}
}
${AUTO_GENERATED_END}`
}

function buildModuleDeclaration(version) {
  const packageName = `widget-react-v${version}`
  return `declare module '${packageName}' {
  import type { ComponentType } from 'react'

  import type { CowSwapWidgetProps } from '@cowprotocol/widget-lib'

  export const CowSwapWidget: ComponentType<CowSwapWidgetProps>
}`
}

function syncDeclarations(pinnedVersions) {
  const moduleDeclarations = pinnedVersions.map(buildModuleDeclaration).join('\n\n')

  fs.writeFileSync(PATHS.declarations, `declare module '*.woff2'\n\n${moduleDeclarations}\n`)
}

function syncPackageJsonAliases(pinnedVersions) {
  const packageJson = readJson(PATHS.packageJson)
  const dependencies = packageJson.dependencies ?? {}

  for (const key of Object.keys(dependencies)) {
    if (key.startsWith('widget-react-v')) {
      delete dependencies[key]
    }
  }

  for (const version of pinnedVersions) {
    dependencies[`widget-react-v${version}`] = `npm:@cowprotocol/widget-react@${version}`
  }

  packageJson.dependencies = dependencies
  fs.writeFileSync(PATHS.packageJson, `${JSON.stringify(packageJson, null, 2)}\n`)
}

async function main() {
  const constantsSource = fs.readFileSync(PATHS.constants, 'utf8')
  const legacyVersions = getLegacyPinnedVersions(constantsSource)

  const localWidgetReactVersion = readJson(PATHS.widgetReactPkg).version
  const localWidgetLibVersion = readJson(PATHS.widgetLibPkg).version
  const npmWidgetReactLatestVersion = await getNpmPackageVersion('@cowprotocol/widget-react')
  const npmWidgetLibLatestVersion = await getWidgetLibVersionForWidgetReact(npmWidgetReactLatestVersion)

  const widgetLibVersionsByVersion = {}
  for (const version of legacyVersions) {
    widgetLibVersionsByVersion[version] = await getWidgetLibVersionForWidgetReact(version)
  }

  const pinnedVersions = [
    npmWidgetReactLatestVersion,
    ...legacyVersions.filter((version) => version !== npmWidgetReactLatestVersion),
  ]

  console.log('Updating widget SDK versions:')
  console.log(`  local widget-react: ${localWidgetReactVersion}`)
  console.log(`  local widget-lib:   ${localWidgetLibVersion}`)
  console.log(`  npm latest react:   ${npmWidgetReactLatestVersion}`)
  console.log(`  npm latest lib:     ${npmWidgetLibLatestVersion}`)

  replaceAutoGeneratedBlock(
    PATHS.constants,
    AUTO_GENERATED_BEGIN,
    AUTO_GENERATED_END,
    buildConstantsBlock({
      localWidgetReactVersion,
      localWidgetLibVersion,
      npmWidgetReactLatestVersion,
      npmWidgetLibLatestVersion,
    }),
  )

  replaceAutoGeneratedBlock(
    PATHS.constants,
    PINNED_LEGACY_BEGIN,
    PINNED_LEGACY_END,
    buildPinnedLegacyBlock(legacyVersions, widgetLibVersionsByVersion),
  )

  replaceAutoGeneratedBlock(
    PATHS.loaders,
    AUTO_GENERATED_BEGIN,
    AUTO_GENERATED_END,
    buildLoadersBlock(pinnedVersions),
  )

  syncDeclarations(pinnedVersions)
  syncPackageJsonAliases(pinnedVersions)

  console.log('\nUpdated widget-sdk-versions.constants.ts, loaders, declarations.d.ts, and package.json.')
  console.log('Run `pnpm install` to refresh lockfile aliases.')
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
