name: Update epics
on:
  issues:
    types: [opened, closed, reopened]
jobs:
  epics:
    runs-on: ubuntu-latest
    name: Update epic issues
    steps:
      - name: Run epics action
        uses: cloudaper/epics-action@4dea9b8b2ccd4778a7c2426d8fd0bed9c9f665e6 # v1.1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          epic-label-name: feature
          auto-close-epic: true
