name: Kanban flow (in progress)

on:
  pull_request:
    types: converted_to_draft

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: CowSwap
          column: In Progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}
