import {
  COW_PROTOCOL_SETTLEMENT_CONTRACT_ADDRESS as COW_PROTOCOL_SETTLEMENT_CONTRACT_ADDRESS_PROD,
  COW_PROTOCOL_SETTLEMENT_CONTRACT_ADDRESS_STAGING,
  COW_PROTOCOL_VAULT_RELAYER_ADDRESS as COW_PROTOCOL_VAULT_RELAYER_ADDRESS_PROD,
  COW_PROTOCOL_VAULT_RELAYER_ADDRESS_STAGING,
} from '@cowprotocol/cow-sdk'

import { isBarnBackendEnv } from './environments'

export const COW_PROTOCOL_SETTLEMENT_CONTRACT_ADDRESS = isBarnBackendEnv
  ? COW_PROTOCOL_SETTLEMENT_CONTRACT_ADDRESS_STAGING
  : COW_PROTOCOL_SETTLEMENT_CONTRACT_ADDRESS_PROD

export const COW_PROTOCOL_VAULT_RELAYER_ADDRESS = isBarnBackendEnv
  ? COW_PROTOCOL_VAULT_RELAYER_ADDRESS_STAGING
  : COW_PROTOCOL_VAULT_RELAYER_ADDRESS_PROD
